answer/urls.py
from django.urls import path

from answer.ajax import get_content, set_content, get_default_content, add_file, execute_anwser, run_tests
from tools.generic_urls import add_url_from_generic_views
from .views import AnswerDocumentUploadView, file_upload_view

app_name = 'answer'
urlpatterns = [
    path('answer/<int:document_id>/get_content/',
         get_content, name='answer_get_content'),
    path('answer/<int:document_id>/set_content/',
         set_content, name='answer_set_content'),
    path('answer/<int:document_id>/get_default_content/',
         get_default_content, name='answer_get_default_content'),
    path('answer/<int:answer_id>/add_file', add_file, name='answer_add_file'),
    path('answer/<int:answer_id>/execute',
         execute_anwser, name='answer_execute'),
    path('answer/<int:answer_id>/test', run_tests, name='answer_test'),
    path('answer/<int:pk>/document/popup/add/',
         AnswerDocumentUploadView.as_view(), name='document_popup_add'),
    path('answer/<int:pk>/document/upload',
         file_upload_view, name='upload_document'),
]

urlpatterns += add_url_from_generic_views('answer.views')

codecheck/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from users.views import UserLoginView

@login_required
def home(request):
    c = {}
    return render(request, "index.html", c)


urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('answer/', include('answer.urls', namespace='answer')),
    path('question/', include('question.urls', namespace='question')),
    path('chapter/', include('chapter.urls', namespace='chapter')),
    path('course/', include('course.urls', namespace='course')),
    path('evaluation/', include('evaluation.urls', namespace='evaluation')),
    path('document/', include('document.urls', namespace='document')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from tools.generic_urls import add_url_from_generic_views
from .views import CourseDetailView, CourseListView
from django.urls import path
app_name = 'course'

urlpatterns = [
    path('', CourseListView.as_view(), name="course_list2"),
    path('<slug:slug>/', CourseDetailView.as_view(), name="course_slug_detail")

] + add_url_from_generic_views('course.views')

question/urls.py
from tools.generic_urls import add_url_from_generic_views
from .views import QuestionPopupCreateView, DocumentUploadView, file_upload_view
from evaluation.views import CriteriaCreateView
from django.urls import path

app_name = 'question'
urlpatterns = [
    path('question/<int:pk>/document/popup/add/', DocumentUploadView.as_view(), name='document_popup_add'),
    path('question/<int:pk>/criteria/popup/add/', CriteriaCreateView.as_view(), name='criteria_popup_add'),
    path('question/<int:pk>/document/upload', file_upload_view, name='upload_document'),
    path('popup/add/', QuestionPopupCreateView.as_view(), name='question_popup_add'),


]

urlpatterns += add_url_from_generic_views('question.views')

users/urls.py
from django.urls import path

from tools.generic_urls import add_url_from_generic_views
from users.profile_views import ProfileUpdateView

app_name = 'users'

urlpatterns = [
                  path('profile/', ProfileUpdateView.as_view(), name='profile_update'),
              ] + add_url_from_generic_views('users.views')

templates/_footer.html
<footer class="bg-light text-center text-lg-start mt-3">
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2021 Copyright
  </div>
</footer>

templates/_modal.html
{% load static i18n crispy_forms_tags %}
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content"></div>
  </div>
</div>

templates/_modal_contact_us.html
<div class="modal fade" id="contactUsModalCenter" tabindex="-1" role="dialog" aria-labelledby="contacUsCenterTitle"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ContactUsLongTitle">{% trans 'Contact us' %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="contactUsForm" name="contactUsForm" class="form-horizontal">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label class="col-md-3 control-label" for="mail_subject">{% trans 'Subject' %}</label>
                            <div class="col-md-9">
                                <input id="mail_subject" name="mail_subject" type="text" class="form-control input-md">
                            </div>
                        </div>
                        <!-- Textarea -->
                        <div class="form-group row">
                            <label class="col-md-3 control-label" for="mail_content">{% trans 'Content' %}</label>
                            <div class="col-md-9">
                                <textarea class="form-control" id="mail_content" name="mail_content"></textarea>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Close' %}</button>
                    <button type="button" id="btn_send_message" class="btn btn-primary">{% trans 'Send message' %}</button>
                </div>
            </div>
        </div>
    </div>

templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block css %}{% endblock css %}
        <!-- CSS only -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.35.0/codemirror.css" rel="stylesheet"
              type="text/css">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">

        {{ form.media }}
    </head>
    <body>
        {% include "nav.html" %}
        <div class="container-fluid">{% block breadcrumbs %}{% endblock %}</div>
        {% include "_modal.html" %}
        <main>
            {% block content %}<div class="container-fluid">base</div>{% endblock content %}
            {% include "_footer.html" %}
        </main>

    <div aria-live="polite" aria-atomic="true" class="position-relative">
        <div class="toast-container position-absolute top-0 end-0 p-3">
            <div id="toast_save" class="toast bg-success" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-body">
                    Saved
                </div>
            </div>
            <div id="toast_error" class="toast bg-danger" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-body">
                    Error
                </div>
            </div>
        </div>
    </div>
    <!-- JavaScript Bundle with Popper -->
    <script src="{% static 'scripts/utils.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.35.0/codemirror.js"></script>
    <script src="https://codemirror.net/mode/python/python.js"></script>
    <script src="http://jonmiles.github.io/bootstrap-treeview/js/bootstrap-treeview.js"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script src="https://rawgit.com/enyo/dropzone/master/dist/dropzone.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js" integrity="sha512-RdSPYh1WA6BF0RhpisYJVYkOyTzK4HwofJ3Q7ivt/jkpW6Vc8AurL1R+4AUcvn9IwEKAPm/fk7qFZW3OuiUDeg==" crossorigin="anonymous"></script>
    <script>
        function delete_document(e){
            var url = $(e).data('url');
            var name = "object";
            bootbox.confirm({
                message: "{% trans "Do you really want to delete" %} <b>"+ $(e).data('name') + "</b> ?",
                buttons: {
                    confirm: {
                        label: "{% trans "Yes" %}",
                        className: 'btn-success'
                    },
                    cancel: {
                        label: "{% trans "No" %}",
                        className: 'btn-danger'
                    }
                },
                callback: function (result) {
                    if (result) {
                        $.ajax({
                            url: url,
                            headers: { "X-CSRFToken": getCookie("csrftoken") },
                            type: 'POST',
                            traditional: true,
                            dataType: 'json',
                            success: function(result){
                                if ($(e).data('source') == "table"){
                                    $(e).closest("tr").remove();
                                }
                                if ($(e).data('source') == "span"){
                                    $(e).closest("span").remove();
                                }
                            },
                            error: function(){
                                $("#toast_error").toast({ delay: 3000 });
                                $("#toast_error").toast('show');
                            }
                        });
                    }
                }
            }); // end bootbox.confirm
        }

        $(document).ready(function () {
            $("select").select2();
            $(".btn-delete").on('click', function(e){delete_document(this);});
            $(".btn-modal").each(function() {
                $( this ).modalForm({ formURL: $( this ).data("url") });
            });
            {% block ready_js %}
            {% endblock %}
        }); // end document

    </script>
    {% block js %}
    {% endblock js %}
</body>

</html>

templates/chapter_popup.html
{% load static i18n crispy_forms_tags crispy_forms_field %}
<form method="post" action="">
    {% csrf_token %}

    <div class="modal-header">
        <h3 class="modal-title">{{title}}</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">

        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>

        {% for field in form %}
        <div class="form-group row">

            {{ field.label_tag }}
            <div class="{{ field_class }}">{% crispy_field field %}{{ field.errors }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="modal-footer">
        <button type="button" class="submit-btn btn btn-primary">Create</button>
    </div>
</form>

templates/form_popup.html
{% load static i18n crispy_forms_tags crispy_forms_field %}
<form method="post" action="">
    {% csrf_token %}

    <div class="modal-header">
        <h3 class="modal-title">{{title}}</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">

        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>

        {% for field in form %}
        <div class="form-group row">

            {{ field.label_tag }}
            <div class="{{ field_class }}">{% crispy_field field %}{{ field.errors }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="modal-footer">
        <button type="button" class="submit-btn btn btn-primary">Create</button>
    </div>
</form>

templates/index.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}


{% block content %}
<div class="container-fluid">
    <div class="row mx-1">
        <div class="col-md-3">
            <div class="form-group">
                <select id="sel_course" class="form-select" aria-label="select course">
                    <option>== Select the course ==</option>
                    {% for c in user.courses.all %}
                    {% if course == c %}
                    <option value="{{c.id}}" selected>{{c}}</option>
                    {% else %}
                    <option value="{{c.id}}">{{c}}</option>
                    {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div id="tree"></div>
        </div>
        <div class="col-md-9">
            {%block right_content %} {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

{% block ready_js %}
$('#sel_course').change(function() {
var url = "{% url 'course:course_detail' 1234 %}".replace(/1234/, $('#sel_course').val().toString());
window.location = url;
});
{% endblock %}

templates/modal_delete.html
{% load static i18n crispy_forms_tags crispy_forms_field %}

    <div class="modal-header">
        <h3 class="modal-title">delete {{object}}</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        Do you really want to delete {{object}} ?
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger submit-btn" data-dismiss="modal">Delete</button>
    </div>

templates/modal_form.html
{% load static i18n crispy_forms_tags crispy_forms_field %}
<div class="modal-header">
    <h3 class="modal-title">{{title}}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form method="post" class="horizontal-form" action="">
    {% csrf_token %}
    <div class="modal-body">
        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
        {% for field in form %}
            <div class="form-group row">
                <label class="col-md-3" for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div class="col-md-9">
                    {% crispy_field field %}
                    <div class="{% if field.errors %} invalid{% endif %}">
                    {% for error in field.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="submit-btn btn btn-primary" data-dismiss="modal">{{btn_label}}</button>
    </div>
</form>

templates/nav.html
{% load static i18n crispy_forms_tags %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'course:course_list2' %}">Courses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>

            </ul>
            <ul class="navbar-nav ml-auto w-100 justify-content-end">
                <li class="nav-item">
                    <button type="button" class="btn nav-link" data-toggle="modal" data-target="#contactUsModalCenter"><i class="far fa-envelope fa-lg"></i></button>
                </li>
                <li>
                    <div class="btn-group" role="group" aria-label="language_group">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                        <a class="btn btn-primary {% if language.code == LANGUAGE_CODE %}active{% endif %}"
                           href="/lang/?lang={{language.code}}&next={{ request.get_full_path }}">
                            {{ language.code| upper }}</a>
                        {% endfor %}
                    </div>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <span class="fa fa-user"></span> {{user.first_name}} {{user.last_name}}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'users:profile_update' %}"><span
                                class="fa fa-id-card"></span> {% trans 'Change Profile' %}</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}?next=/">
                            <span class="fa fa-cog"></span> {% trans 'Password change' %}</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}?next=/">
                            <span class="fas fa-sign-out-alt"></span> {% trans 'Log out' %}</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}?next=/"><span class="fa fa-user"></span> {% trans 'Sign in' %}</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/update.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}

{% block content %}
<div class="row">
    <h2 class="text-center">{{object}}</h2>
</div>
<div class="container">
    {% crispy form %}
</div>
{% endblock %}

templates/update_question.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags crispy_forms_field %}

{% block breadcrumbs %}
<div class="row pl-3">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'course:course_list' %}">Courses</a></li>
            <li class="breadcrumb-item"><a href="{% url 'course:course_detail' object.refer_chapter.refer_course.id %}">{{object.refer_chapter.refer_course.name}}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'chapter:chapter_detail' object.refer_chapter.id %}">{{object.refer_chapter.name}}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'question:question_detail' object.id %}">{{object.name}}</a></li>
            <li class="breadcrumb-item active"><a href="#">change</a></li>
        </ol>
    </nav>
</div>
{%endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h2 class="text-center">{{object}}</h2>
        </div>
    </div>
    <form action="" method="POST">
        {% csrf_token %}
        <!-- name -->
        <div class="form-group form-horizontal row">
            <label for="{{ form.name.id_for_label }}" class=" col-md-3 form-check-label{% if form.name.field.required %} requiredField{% endif %}">
                        {{ form.name.label|safe }}{% if form.name.field.required %}<span class="asteriskField">*</span>{% endif %}
                    </label>
            <div class="col-md-9">
                    {% crispy_field form.name %}
            </div>
        </div>
        <!-- question -->
        <div class="form-group form-horizontal row">
            <label for="{{ form.question.id_for_label }}" class="col-md-3 form-check-label{% if form.question.field.required %} requiredField{% endif %}">
                        {{ form.question.label|safe }}{% if form.question.field.required %}<span class="asteriskField">*</span>{% endif %}
                    </label>
            <div class="col-md-9">
                    {% crispy_field form.question %}
            </div>
        </div>
        <!-- documents -->
        <div class="form-group form-horizontal row">
            <label class="col-md-3 form-check-label">Documents</label>
            <div class="col-md-9">
                <table id="table_documents" style="border: 1px solid #aaa;margin-bottom: 4px;" class="table table-striped table-sm">
                    <thead>
                        <tr><th class="pl-3" colspan="2">Name</th></tr>
                    </thead>
                    <tbody>
                        {% for filename, buttons in documents %}
                            <tr>
                                <td>{{ filename }}</td>
                                <td style="width:1px; white-space:nowrap;text-align:right;">{{ buttons | safe}}</td>
                            </tr>
                            {% empty %}
                                <tr><td colspan="2">No objects</td></tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="#" id="#btn_add_documents" class="btn btn-secondary btn-sm btn-modal" data-url="{% url 'question:document_popup_add' object.id  %}?type=doc">Add Document</a>
            </div>
        </div>
        <!-- can_add_documents -->
        <div class="form-group form-horizontal row">
            <label for="{{ form.can_add_documents.id_for_label }}" class="col-md-3 form-check-label{% if form.can_add_documents.field.required %} requiredField{% endif %}">
                        {{ form.can_add_documents.label|safe }}{% if form.can_add_documents.field.required %}<span class="asteriskField">*</span>{% endif %}
                    </label>
            <div class="col-md-9">
                    {% crispy_field form.can_add_documents %}
            </div>
        </div>
        <!-- languages -->
        <div class="form-group form-horizontal row">
            <label for="{{ form.languages.id_for_label }}" class="col-md-3 form-check-label{% if form.languages.field.required %} requiredField{% endif %}">
                        {{ form.languages.label|safe }}{% if form.languages.field.required %}<span class="asteriskField">*</span>{% endif %}
                    </label>
            <div class="col-md-9">
                    {% crispy_field form.languages %}
            </div>
        </div>
        <!-- can_add_code -->
        <div class="form-group form-horizontal row">
            <label for="{{ form.can_add_code.id_for_label }}" class="col-md-3 form-check-label{% if form.can_add_code.field.required %} requiredField{% endif %}">
                        {{ form.can_add_code.label|safe }}{% if form.can_add_code.field.required %}<span class="asteriskField">*</span>{% endif %}
                    </label>
            <div class="col-md-9">
                    {% crispy_field form.can_add_code %}
            </div>
        </div>
        <!-- codes -->
        <div class="form-group form-horizontal row">
            <label class="col-md-3 form-check-label">Default codes</label>
            <div class="col-md-9">
                <table id="table_codes" style="border: 1px solid #aaa;margin-bottom: 4px;" class="table table-striped table-sm">
                    <thead>
                        <tr><th class="pl-3" colspan="2">Name</th></tr>
                    </thead>
                    <tbody>
                        {% for filename, buttons in codes %}
                            <tr>
                                <td>{{ filename }}</td>
                                <td style="width:1px; white-space:nowrap;text-align:right;">{{ buttons | safe }}</td>
                            </tr>
                            {% empty %}
                                <tr><td colspan="2">No objects</td></tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="#" id="#btn_add_default_code" class="btn btn-secondary btn-sm btn-modal" data-url="{% url 'question:document_popup_add' object.id  %}?type=code">Add code</a>
            </div>
        </div>
        <!-- criteria -->
        <div class="form-group form-horizontal row">
            <label class="col-md-3 form-check-label">Criteria</label>
            <div class="col-md-9">
                <table id="table_criterias" style="border: 1px solid #aaa;margin-bottom: 4px;" class="table table-striped table-sm">
                    <thead>
                        <tr><th class="pl-3">Name</th><th>max points</th><th>step</th><th></th></tr>
                    </thead>
                    <tbody>
                        {% for name, detail, max_points, step, buttons in criterias %}
                            <tr>
                                <td>{{ name }}{{detail}}</td>
                                <td>{{ max_points }}</td>
                                <td>{{ step }}</td>
                                <td style="width:1px; white-space:nowrap;text-align:right;">{{ buttons | safe }}</td>
                            </tr>
                            {% empty %}
                                <tr><td colspan="4">No objects</td></tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="#" id="#btn_add_criteria" class="btn btn-secondary btn-sm btn-modal" data-url="{% url 'question:criteria_popup_add' object.id  %}">Add criteria</a>
            </div>
        </div>
        <!-- allow_pair_evaluation -->
        <div class="form-group form-horizontal row">
            <label for="{{ form.allow_pair_evaluation.id_for_label }}" class="col-md-3 form-check-label{% if form.allow_pair_evaluation.field.required %} requiredField{% endif %}">
                        {{ form.allow_pair_evaluation.label|safe }}{% if form.allow_pair_evaluation.field.required %}<span class="asteriskField">*</span>{% endif %}
                    </label>
            <div class="col-md-9">
                    {% crispy_field form.can_add_code %}
            </div>
        </div>
        <!-- answers -->
        <div class="form-group form-horizontal row">
            <label class="col-md-3 form-check-label">Answers</label>
            <div class="col-md-9">
                <table style="border: 1px solid #aaa;" class="table table-striped table-sm">
                    <thead>
                        <tr><th class="pl-3" colspan="2">Name</th></tr>
                    </thead>
                    <tbody>
                        {% for filename, buttons in answers %}
                            <tr>
                                <td>{{ filename }}</td>
                                <td style="width:1px; white-space:nowrap;text-align:right;">{{ buttons |safe }}</td>
                            </tr>
                            {% empty %}
                                <tr><td colspan="2">No objects</td></tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- buttons -->
        <div class="form-group row">
            <div class="aab col-md-3"></div>
            <div class="col-md-9"> <input type="submit" name="submit" value="Save" class="btn btn-primary" id="submit-id-submit"> </div>
        </div>
    </form>
</div>
{% endblock %}